prgr/city_problems/urls.py
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import TemplateView, CreateView, RedirectView
import django.contrib.auth.urls
# noinspection PyUnresolvedReferences
from city_problems.views import test_request
from .cbv import *


app_name = 'city'

urlpatterns = [
    path('', ProblemListView.as_view(), name='index_list'),
    path('add_problem/', ProblemCreate.as_view(), name='create_problem'),
    path('profile/', UserProfile.as_view(), name='user_profile'),
    #path('logout/', ProblemListView.as_view(), name='tester'),
    path('problem/<int:pk>', ProblemDetail.as_view(), name='problem_detail'),
    path('problem/<int:pk>/update', ProblemUpdate.as_view(), name='problem_update'),
    path('problem/<int:pk>/delete', ProblemDelete.as_view(), name='problem_delete'),
    path('test/', test_request, name='test'),
    path('accounts/profile/', RedirectView.as_view(url='/', permanent=False)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('add-comment/', CommentCreate.as_view(), name='create-comment'),
    path('create-vote/', CreateVote.as_view(), name='create-vote')
]

prgr/prgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('city_problems.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prgr/city_problems/models/comment.py
from django.conf import settings
from django.db import models

from .problem import Problem


class Comment(models.Model):
    date_created = models.DateTimeField()
    text = models.CharField(max_length=500)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-date_created']
    def __str__(self):
        return f"{self.text}  {self.problem.short_name}"

prgr/city_problems/models/problem.py
from django.db import models

from django.conf import settings
from django.urls import reverse

from .status import Status


class Problem(models.Model):
    creation_date = models.DateTimeField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True)
    image = models.ImageField() #TODO production ready deployment - nginx
    short_name = models.CharField(max_length=140)
    description = models.CharField(max_length=3000)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-creation_date']

    def __str__(self):
        return self.short_name

    def get_absolute_url(self):
        return reverse('city:problem_detail', kwargs={'pk': self.pk})

prgr/city_problems/models/status.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

prgr/city_problems/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .problem import Problem

class User(AbstractUser):
    pass

prgr/city_problems/models/vote.py
from django.conf import settings
from django.db import models

from .problem import Problem


class Vote(models.Model):
    vote_date = models.DateTimeField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-vote_date']
    def __str__(self):
        return f"{self.problem.short_name}  {self.user.username}"

prgr/city_problems/forms.py
from django.forms import ModelForm
from .models import Problem

class ContactForm(ModelForm):
    class Meta:
        model = Problem
        fields = ['status', 'short_name']

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        print("Success post")

prgr/city_problems/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.list import ListView
from .models import Problem
from django.utils import timezone


class ProblemListView(ListView):

    model = Problem
    paginate_by = 100
    template_name = "city_problems/problem_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

def test_request(request):
    string = ""
    for key, value in request.headers.items():
        string += f"<p>{key}-{value}</p>"

    return HttpResponse(string)

prgr/city_problems/templates/city_problems/add_problem.html
{% extends "city_problems/main_template.html" %}
{% block content %}
<form action="/add_problem/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

prgr/city_problems/templates/city_problems/contact.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

prgr/city_problems/templates/city_problems/main_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Проблемы города</title>
</head>
<body>
<header>
    <nav>
        <ul>
            <a href="{% url 'city:index_list' %}">
                <li>Главная</li>
            </a>
            {% if user.is_authenticated %}
                <a href="{% url 'city:create_problem' %}">
                    <li>Добавить проблему</li>
                </a>
                <a href="{% url 'city:user_profile' %}">
                    <li>Профиль</li>
                 </a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'city:logout' %}">
                    <li>Выйти</li>
                </a>
            {% else %}
                <a href="{% url 'city:login' %}">
                    <li>Войти</li>
                </a>
            {% endif %}
        </ul>
    </nav>
</header>
<main>
    <div>{% block content %}{% endblock %}</div>
</main>
<footer>
    <p>Добавил проблему - решил проблему</p>
</footer>
</body>
</html>

prgr/city_problems/templates/city_problems/problem_confirm_delete.html
{% extends "city_problems/main_template.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Уверены, что хотите удалить проблему?</h1>
        <input type="submit" value="Да, удалить">
    <article>
        <h2><a href="{% url 'city:problem_detail' problem.id %}">{{ problem.short_name }}</a></h2>
        <p>{{ problem.description }}</p>
        <img src="{{ MEDIA_URL }}{{ problem.image }}" style="width: 20%; height: 20%">
        <p>{{ problem.creation_date }}</p>
        <p>{{ problem.status }}</p>
    </article>

</form>
{% endblock %}

prgr/city_problems/templates/city_problems/problem_detail.html
{% extends "city_problems/main_template.html" %}

{% block content %}
    <article>
        <h2><a href="{% url 'city:problem_detail' problem.id %}">{{ problem.short_name }}</a></h2>
        <p>{{ problem.description }}</p>
        <img src="{{ MEDIA_URL }}{{ problem.image }}" style="width: 20%; height: 20%">
        <p>{{ problem.creation_date }}</p>
        <p>{{ problem.status }}</p>
        <p>{{ problem.user }}</p>
        {% if user ==  problem.user%}
        <p><a href="{% url 'city:problem_update' problem.id %}">Изменить</a>
            <a href="{% url 'city:problem_delete' problem.id %}">Удалить</a></p>
        {% endif %}
    {% if user.is_authenticated %}
        <div>
            <form action="{% url 'city:create-vote' %}" method="post">
                {% csrf_token %}
                {{ vote_form.as_p }}
                {% if vote_exists %}
                <input type="submit" value="Вы уже голосовали" disabled>
                    {% else %}
                     <input type="submit" value="Проголосовать">
                    {% endif %}
            </form>
        </div>
    {% endif %}
    </article>
    <div>
    <p>Всего голосов {{ votes|length }}</p>
    {% for vote in votes %}
    <article>
            <p>{{ vote.vote_date}}</p>
            <p>Автор: {{ vote.user }}</p>
    </article>
{% empty %}
    <h2>У этой проблемы еще не комментариев</h2>
{% endfor %}
    </div>
    <div>
        {% for comment in comments %}
    <article>
            <p>{{ comment.text }}</p>
            <p>{{ comment.date_created }}</p>
            <p>Автор: {{ comment.user }}</p>
    </article>
{% empty %}
    <h2>У этой проблемы еще не комментариев</h2>
{% endfor %}
    </div>
     {% if user.is_authenticated %}
        <div>
            <form action="{% url 'city:create-comment' %}" method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <input type="submit" value="Добавить комментарий">
            </form>
        </div>
    {% endif %}
{% endblock %}

prgr/city_problems/templates/city_problems/problem_form.html
{% extends "city_problems/main_template.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

prgr/city_problems/templates/city_problems/problem_list.html
{% extends "city_problems/main_template.html" %}
{% block content %}
<h1>Актуальные городские проблемы</h1>

{% for problem in object_list %}
    <article>
        <h2><a href="{% url 'city:problem_detail' problem.id %}">{{ problem.short_name }}</a></h2>
        <p>{{ problem.description }}</p>
        <img src="{{ MEDIA_URL }}{{ problem.image }}" style="width: 20%; height: 20%">
        <p>{{ problem.creation_date }}</p>
        <p>{{ problem.status }}</p>
        <p>{{ problem.user }}</p>
         {% if user ==  problem.user%}
        <p><a href="{% url 'city:problem_update' problem.id %}">Изменить</a></p>
        {% endif %}
    </article>
{% empty %}
    <h2>В этом городе нет проблем!</h2>
{% endfor %}

{% endblock %}

prgr/city_problems/templates/city_problems/user_profile.html
{% extends "city_problems/main_template.html" %}
{% block content %}
<h1>Привет, {{ user }}</h1>
<h1>Проблемы добавленные пользователем</h1>

{% for problem in problems %}
    <article>
        <h2><a href="{% url 'city:problem_detail' problem.id %}">{{ problem.short_name }}</a></h2>
        <p>{{ problem.description }}</p>
        <img src="{{ MEDIA_URL }}{{ problem.image }}" style="width: 20%; height: 20%">
        <p>{{ problem.creation_date }}</p>
        <p>{{ problem.status }}</p>
        <p>{{ problem.user }}</p>
        <p><a href="{% url 'city:problem_update' problem.id %}">Изменить</a></p>
    </article>
{% empty %}
    <h2>Вы еше не добавили проблем)))</h2>
{% endfor %}
    <h1>Ваши комментарии</h1>
            {% for comment in comments %}
    <article>
            <p>{{ comment.text }}</p>
            <p>{{ comment.date_created }}</p>
            <p>Автор: {{ comment.user }}</p>
            <p>Проблема: {{ comment.problem }}</p>
    </article>
{% empty %}
    <h2>У этой проблемы еще не комментариев</h2>
{% endfor %}
        <h1>Ваши голоса:</h1>

            {% for vote in votes %}
    <article>
            <p>{{ vote.vote_date}}</p>
            <p>Автор: {{ vote.user }}</p>
            <p>Проблема: {{ vote.problem }}</p>
    </article>
{% empty %}
    <h2>У этой проблемы еще не комментариев</h2>
{% endfor %}

{% endblock %}